<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ApplicationIcon>Content/Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <MonoGameContentReference Include="Content\Particles.mgcb" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Monogame\Monogame.csproj" />
  </ItemGroup>
</Project>
