<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Tourmi.EntityComponentSystem" />
    <Using Include="Tourmi.EntityComponentSystem.Components" />
    <Using Include="Tourmi.EntityComponentSystem.Components.Relations" />
    <Using Include="Tourmi.EntityComponentSystem.Components.Tags" />
    <Using Include="Tourmi.EntityComponentSystem.Entities" />
    <Using Include="Tourmi.EntityComponentSystem.Ids" />
    <Using Include="Tourmi.EntityComponentSystem.Relations" />
  </ItemGroup>
</Project>
